#!/bin/bash
# アプリケーション状態確認スクリプト

EC2_IP="3.112.247.189"
KEY_FILE="your-key.pem"

echo "=== EC2インスタンスへSSH接続 ==="
echo "ssh -i $KEY_FILE ec2-user@$EC2_IP"
echo ""
echo "接続後、以下のコマンドを実行してください："
echo ""
echo "# 1. アプリケーションサービスの状態確認"
echo "sudo systemctl status payment-app"
echo ""
echo "# 2. アプリケーションログ確認"
echo "sudo journalctl -u payment-app -n 50 --no-pager"
echo ""
echo "# 3. アプリケーションディレクトリ確認"
echo "ls -la /home/ec2-user/demo-app/app/"
echo ""
echo "# 4. Node.jsプロセス確認"
echo "ps aux | grep node"
echo ""
echo "# 5. ポート3000のリスニング確認"
echo "sudo netstat -tlnp | grep 3000"
echo ""
echo "# 6. ローカルでヘルスチェック"
echo "curl http://localhost:3000/health"
echo ""
echo "# 7. 環境変数確認"
echo "sudo systemctl show payment-app --property=Environment"
echo ""
echo "# 8. GitHubからのクローン確認"
echo "ls -la /home/ec2-user/"
echo ""
echo "# 9. npm依存関係確認"
echo "cd /home/ec2-user/demo-app/app && npm list"
echo ""
echo "# 10. 手動でアプリ起動テスト"
echo "cd /home/ec2-user/demo-app/app && node app.js"
